spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-oauth-url}
          jwk-set-uri: ${keycloak.base-oauth-url}/protocol/openid-connect/certs
          audience: LDAP-ACCOUNT-TRANSFER-API
    
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs